#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x97D9123DE37A484F (toso@posteo.net)
#
Name     : spice-gtk
Version  : 0.37
Release  : 32
URL      : https://www.spice-space.org/download/gtk/spice-gtk-0.37.tar.bz2
Source0  : https://www.spice-space.org/download/gtk/spice-gtk-0.37.tar.bz2
Source1 : https://www.spice-space.org/download/gtk/spice-gtk-0.37.tar.bz2.sig
Summary  : SPICE Client Gtk 3.0 library
Group    : Development/Tools
License  : LGPL-2.1
Requires: spice-gtk-bin = %{version}-%{release}
Requires: spice-gtk-data = %{version}-%{release}
Requires: spice-gtk-lib = %{version}-%{release}
Requires: spice-gtk-license = %{version}-%{release}
Requires: spice-gtk-locales = %{version}-%{release}
Requires: spice-gtk-man = %{version}-%{release}
Requires: clr-hardware-files
BuildRequires : acl-dev
BuildRequires : asciidoc
BuildRequires : buildreq-meson
BuildRequires : clr-hardware-files
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : glibc-staticdev
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gst-plugins-bad
BuildRequires : gst-plugins-base-dev
BuildRequires : gst-plugins-good
BuildRequires : gst-plugins-ugly
BuildRequires : gstreamer-dev
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libxslt-bin
BuildRequires : lz4-dev
BuildRequires : opus-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : pkgconfig(spice-protocol)
BuildRequires : pkgconfig(x11)
BuildRequires : pyparsing
BuildRequires : usbredir-dev
BuildRequires : vala
Patch1: CVE-2017-12194.nopatch

%description
spice-gtk
=========
A Gtk client and libraries for SPICE remote desktop servers.

%package bin
Summary: bin components for the spice-gtk package.
Group: Binaries
Requires: spice-gtk-data = %{version}-%{release}
Requires: spice-gtk-license = %{version}-%{release}

%description bin
bin components for the spice-gtk package.


%package data
Summary: data components for the spice-gtk package.
Group: Data

%description data
data components for the spice-gtk package.


%package dev
Summary: dev components for the spice-gtk package.
Group: Development
Requires: spice-gtk-lib = %{version}-%{release}
Requires: spice-gtk-bin = %{version}-%{release}
Requires: spice-gtk-data = %{version}-%{release}
Provides: spice-gtk-devel = %{version}-%{release}
Requires: spice-gtk = %{version}-%{release}

%description dev
dev components for the spice-gtk package.


%package doc
Summary: doc components for the spice-gtk package.
Group: Documentation
Requires: spice-gtk-man = %{version}-%{release}

%description doc
doc components for the spice-gtk package.


%package lib
Summary: lib components for the spice-gtk package.
Group: Libraries
Requires: spice-gtk-data = %{version}-%{release}
Requires: spice-gtk-license = %{version}-%{release}

%description lib
lib components for the spice-gtk package.


%package license
Summary: license components for the spice-gtk package.
Group: Default

%description license
license components for the spice-gtk package.


%package locales
Summary: locales components for the spice-gtk package.
Group: Default

%description locales
locales components for the spice-gtk package.


%package man
Summary: man components for the spice-gtk package.
Group: Default

%description man
man components for the spice-gtk package.


%prep
%setup -q -n spice-gtk-0.37
cd %{_builddir}/spice-gtk-0.37

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572558598
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-gtk=3.0 \
--enable-usbredir=yes \
--enable-vala \
--with-usb-ids-path=/usr/share/hwdata/usb.ids
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1572558598
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/spice-gtk
cp %{_builddir}/spice-gtk-0.37/COPYING %{buildroot}/usr/share/package-licenses/spice-gtk/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/spice-gtk-0.37/subprojects/spice-common/COPYING %{buildroot}/usr/share/package-licenses/spice-gtk/3704f4680301a60004b20f94e0b5b8c7ff1484a9
%make_install
%find_lang spice-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/spice-client-glib-usb-acl-helper
/usr/bin/spicy
/usr/bin/spicy-screenshot
/usr/bin/spicy-stats

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/SpiceClientGLib-2.0.typelib
/usr/lib64/girepository-1.0/SpiceClientGtk-3.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.spice-space.lowlevelusbaccess.policy
/usr/share/vala/vapi/spice-client-glib-2.0.deps
/usr/share/vala/vapi/spice-client-glib-2.0.vapi
/usr/share/vala/vapi/spice-client-gtk-3.0.deps
/usr/share/vala/vapi/spice-client-gtk-3.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/spice-client-glib-2.0/channel-cursor.h
/usr/include/spice-client-glib-2.0/channel-display.h
/usr/include/spice-client-glib-2.0/channel-inputs.h
/usr/include/spice-client-glib-2.0/channel-main.h
/usr/include/spice-client-glib-2.0/channel-playback.h
/usr/include/spice-client-glib-2.0/channel-port.h
/usr/include/spice-client-glib-2.0/channel-record.h
/usr/include/spice-client-glib-2.0/channel-smartcard.h
/usr/include/spice-client-glib-2.0/channel-usbredir.h
/usr/include/spice-client-glib-2.0/channel-webdav.h
/usr/include/spice-client-glib-2.0/qmp-port.h
/usr/include/spice-client-glib-2.0/smartcard-manager.h
/usr/include/spice-client-glib-2.0/spice-audio.h
/usr/include/spice-client-glib-2.0/spice-channel.h
/usr/include/spice-client-glib-2.0/spice-client.h
/usr/include/spice-client-glib-2.0/spice-file-transfer-task.h
/usr/include/spice-client-glib-2.0/spice-glib-enums.h
/usr/include/spice-client-glib-2.0/spice-option.h
/usr/include/spice-client-glib-2.0/spice-session.h
/usr/include/spice-client-glib-2.0/spice-types.h
/usr/include/spice-client-glib-2.0/spice-uri.h
/usr/include/spice-client-glib-2.0/spice-util.h
/usr/include/spice-client-glib-2.0/spice-version.h
/usr/include/spice-client-glib-2.0/usb-device-manager.h
/usr/include/spice-client-gtk-3.0/spice-client-gtk.h
/usr/include/spice-client-gtk-3.0/spice-grabsequence.h
/usr/include/spice-client-gtk-3.0/spice-gtk-session.h
/usr/include/spice-client-gtk-3.0/spice-widget-enums.h
/usr/include/spice-client-gtk-3.0/spice-widget.h
/usr/include/spice-client-gtk-3.0/usb-device-widget.h
/usr/lib64/libspice-client-glib-2.0.so
/usr/lib64/libspice-client-gtk-3.0.so
/usr/lib64/pkgconfig/spice-client-glib-2.0.pc
/usr/lib64/pkgconfig/spice-client-gtk-3.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/spice-gtk/SpiceAudio.html
/usr/share/gtk-doc/html/spice-gtk/SpiceChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceCursorChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceDisplay.html
/usr/share/gtk-doc/html/spice-gtk/SpiceDisplayChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceFileTransferTask.html
/usr/share/gtk-doc/html/spice-gtk/SpiceGtkSession.html
/usr/share/gtk-doc/html/spice-gtk/SpiceInputsChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceMainChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpicePlaybackChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpicePortChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceRecordChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSession.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSmartcardChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSmartcardManager.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbDeviceManager.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbDeviceWidget.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbredirChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceWebdavChannel.html
/usr/share/gtk-doc/html/spice-gtk/annotation-glossary.html
/usr/share/gtk-doc/html/spice-gtk/api-index-full.html
/usr/share/gtk-doc/html/spice-gtk/api-reference.html
/usr/share/gtk-doc/html/spice-gtk/application-support.html
/usr/share/gtk-doc/html/spice-gtk/ch01.html
/usr/share/gtk-doc/html/spice-gtk/ch02.html
/usr/share/gtk-doc/html/spice-gtk/ch03.html
/usr/share/gtk-doc/html/spice-gtk/home.png
/usr/share/gtk-doc/html/spice-gtk/index.html
/usr/share/gtk-doc/html/spice-gtk/left-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/left.png
/usr/share/gtk-doc/html/spice-gtk/object-tree.html
/usr/share/gtk-doc/html/spice-gtk/right-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/right.png
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-SpiceQmpPort.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-SpiceURI.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-Utilities.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-spice-version.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk.devhelp2
/usr/share/gtk-doc/html/spice-gtk/style.css
/usr/share/gtk-doc/html/spice-gtk/up-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspice-client-glib-2.0.so.8
/usr/lib64/libspice-client-glib-2.0.so.8.6.0
/usr/lib64/libspice-client-gtk-3.0.so.5
/usr/lib64/libspice-client-gtk-3.0.so.5.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/spice-gtk/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/spice-gtk/3704f4680301a60004b20f94e0b5b8c7ff1484a9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/spice-client.1

%files locales -f spice-gtk.lang
%defattr(-,root,root,-)

