#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spice-gtk
Version  : 0.31
Release  : 3
URL      : http://spice-space.org/download/gtk/spice-gtk-0.31.tar.bz2
Source0  : http://spice-space.org/download/gtk/spice-gtk-0.31.tar.bz2
Summary  : SPICE Client Gtk 2.0 library
Group    : Development/Tools
License  : LGPL-2.1
Requires: spice-gtk-bin
Requires: spice-gtk-lib
Requires: spice-gtk-doc
Requires: spice-gtk-locales
Requires: spice-gtk-data
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libjpeg-turbo-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(epoxy)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(spice-protocol)
BuildRequires : pkgconfig(usbutils)

%description
spice-gtk
=========
A Gtk client and libraries for SPICE remote desktop servers.

%package bin
Summary: bin components for the spice-gtk package.
Group: Binaries
Requires: spice-gtk-data

%description bin
bin components for the spice-gtk package.


%package data
Summary: data components for the spice-gtk package.
Group: Data

%description data
data components for the spice-gtk package.


%package dev
Summary: dev components for the spice-gtk package.
Group: Development
Requires: spice-gtk-lib
Requires: spice-gtk-bin
Requires: spice-gtk-data
Provides: spice-gtk-devel

%description dev
dev components for the spice-gtk package.


%package doc
Summary: doc components for the spice-gtk package.
Group: Documentation

%description doc
doc components for the spice-gtk package.


%package lib
Summary: lib components for the spice-gtk package.
Group: Libraries
Requires: spice-gtk-data

%description lib
lib components for the spice-gtk package.


%package locales
Summary: locales components for the spice-gtk package.
Group: Default

%description locales
locales components for the spice-gtk package.


%prep
%setup -q -n spice-gtk-0.31

%build
%configure --disable-static --with-gtk=2.0
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang spice-gtk

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/spicy
/usr/bin/spicy-screenshot
/usr/bin/spicy-stats

%files data
%defattr(-,root,root,-)
/usr/share/vala/vapi/spice-protocol.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/spice-client-glib-2.0/channel-cursor.h
/usr/include/spice-client-glib-2.0/channel-display.h
/usr/include/spice-client-glib-2.0/channel-inputs.h
/usr/include/spice-client-glib-2.0/channel-main.h
/usr/include/spice-client-glib-2.0/channel-playback.h
/usr/include/spice-client-glib-2.0/channel-port.h
/usr/include/spice-client-glib-2.0/channel-record.h
/usr/include/spice-client-glib-2.0/channel-smartcard.h
/usr/include/spice-client-glib-2.0/channel-usbredir.h
/usr/include/spice-client-glib-2.0/channel-webdav.h
/usr/include/spice-client-glib-2.0/smartcard-manager.h
/usr/include/spice-client-glib-2.0/spice-audio.h
/usr/include/spice-client-glib-2.0/spice-channel-enums.h
/usr/include/spice-client-glib-2.0/spice-channel.h
/usr/include/spice-client-glib-2.0/spice-client.h
/usr/include/spice-client-glib-2.0/spice-file-transfer-task.h
/usr/include/spice-client-glib-2.0/spice-glib-enums.h
/usr/include/spice-client-glib-2.0/spice-option.h
/usr/include/spice-client-glib-2.0/spice-session.h
/usr/include/spice-client-glib-2.0/spice-types.h
/usr/include/spice-client-glib-2.0/spice-uri.h
/usr/include/spice-client-glib-2.0/spice-util.h
/usr/include/spice-client-glib-2.0/spice-version.h
/usr/include/spice-client-glib-2.0/usb-device-manager.h
/usr/include/spice-client-gtk-2.0/spice-client-gtk.h
/usr/include/spice-client-gtk-2.0/spice-grabsequence.h
/usr/include/spice-client-gtk-2.0/spice-gtk-session.h
/usr/include/spice-client-gtk-2.0/spice-widget-enums.h
/usr/include/spice-client-gtk-2.0/spice-widget.h
/usr/include/spice-client-gtk-2.0/usb-device-widget.h
/usr/include/spice-controller/spice-controller.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
/usr/share/gtk-doc/html/spice-gtk/SpiceAudio.html
/usr/share/gtk-doc/html/spice-gtk/SpiceChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceCursorChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceDisplay.html
/usr/share/gtk-doc/html/spice-gtk/SpiceDisplayChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceFileTransferTask.html
/usr/share/gtk-doc/html/spice-gtk/SpiceGtkSession.html
/usr/share/gtk-doc/html/spice-gtk/SpiceInputsChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceMainChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpicePlaybackChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpicePortChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceRecordChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSession.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSmartcardChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceSmartcardManager.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbDeviceManager.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbDeviceWidget.html
/usr/share/gtk-doc/html/spice-gtk/SpiceUsbredirChannel.html
/usr/share/gtk-doc/html/spice-gtk/SpiceWebdavChannel.html
/usr/share/gtk-doc/html/spice-gtk/annotation-glossary.html
/usr/share/gtk-doc/html/spice-gtk/api-index-deprecated.html
/usr/share/gtk-doc/html/spice-gtk/api-index-full.html
/usr/share/gtk-doc/html/spice-gtk/api-reference.html
/usr/share/gtk-doc/html/spice-gtk/application-support.html
/usr/share/gtk-doc/html/spice-gtk/ch01.html
/usr/share/gtk-doc/html/spice-gtk/ch02.html
/usr/share/gtk-doc/html/spice-gtk/ch03.html
/usr/share/gtk-doc/html/spice-gtk/home.png
/usr/share/gtk-doc/html/spice-gtk/index.html
/usr/share/gtk-doc/html/spice-gtk/index.sgml
/usr/share/gtk-doc/html/spice-gtk/left-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/left.png
/usr/share/gtk-doc/html/spice-gtk/object-tree.html
/usr/share/gtk-doc/html/spice-gtk/right-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/right.png
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-SpiceURI.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-Utilities.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk-Version-Information.html
/usr/share/gtk-doc/html/spice-gtk/spice-gtk.devhelp2
/usr/share/gtk-doc/html/spice-gtk/style.css
/usr/share/gtk-doc/html/spice-gtk/up-insensitive.png
/usr/share/gtk-doc/html/spice-gtk/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f spice-gtk.lang 
%defattr(-,root,root,-)

